spring:
  application.name: langchain4j-nutrition-planner
  profiles.default: openai
  threads.virtual.enabled: true
  security.user:
    password: 123456
    name: alice

management:
  endpoints.web.exposure.include: "*"
  otlp.metrics.export.enabled: false
  tracing.export.otlp.enabled: false

nutrition-planner:
  user-profiles:
    - username: alice
      dietary-restrictions:
        - vegetarian
      health-goals:
        - weight-loss
        - improve-energy
      daily-calorie-target: 1800
      allergies:
        - nuts
      disliked-ingredients:
        - cilantro
        - olives
