spring:
  ai:
    model.chat: openai
    openai:
      api-key: ${OPENAI_API_KEY}
      chat.model: ${OPENAI_MODEL_NAME:gpt-4o}

nutrition-planner:
  provider: OpenAI
  model: ${spring.ai.openai.chat.model}
