spring:
  ai:
    # Define AI provider(s) for type of models for autoconfiguration
    model:
      chat: openai
    # AI provider configuration
    openai:
      api-key: ${OPENAI_API_KEY}
      chat.model: ${OPENAI_MODEL_NAME:gpt-4o}