server.servlet.session.cookie.name: NUTRITION_SPRING_AI_SESSION

spring:
  application.name: nutrition-planner
  profiles.default: openai
  threads.virtual.enabled: true
  security.user:
      password: 123456
      name: alice
  ai:
    # Define AI provider(s) for type of models for autoconfiguration
    model:
      chat: none
      embedding: none
      image: none
      audio:
        speech: none
        transcription: none
      moderation: none
    tools.observations.include-content: false
    mcp.server:
      name: ${spring.application.name}
      protocol: STREAMABLE
      streamable-http.mcp-endpoint: /mcp

management:
  endpoints.web.exposure.include: "*"
  otlp.metrics.export.enabled: false
  tracing.export.enabled: false
  logging.export.enabled: false

logging.level:
  org.springaicommunity: info
  org.springframework.ai: info

nutrition-planner:
  user-profiles:
    - name: alice
      dietary-restrictions:
        - vegetarian
      health-goals:
        - weight-loss
        - improve-energy
      daily-calorie-target: 1800
      allergies:
        - nuts
      disliked-ingredients:
        - cilantro
        - olives
